FROM tsdkelly/crosscompilepi:v1

# Avoid user interaction with tzdata
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get dist-upgrade && \
    apt-get install libx264-dev libx11-dev -y && \
    apt-get clean 