name: Build Macos Static

env:
  project: PopH264

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*Test*' 

jobs:
  Build:
    name: Macos Static Library
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build Macos Static
        uses: NewChromantics/PopAction_BuildApple@v1.0.11
        with:
          BuildScheme: ${{ env.project }}_MacosStatic
          project: ${{ env.project }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          # tsdk: these env vars are set in each of the actions
          # gr: 1.2.X changes these to outputs
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_DIR }}
          if-no-files-found: error
