name: Build Linux

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    env:
      project: PopH264
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            type: linux
            architecture: x86_64

          - os: Nvidia
            type: linux
            architecture: arm64

          - os: ubuntu-latest
            type: linux
            architecture: armv8
            flag: pi

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Linux
        uses: NewChromantics/PopAction_BuildLinux@v1
        with:
          os: ${{ matrix.config.os }}
          project: ${{ env.project }}
          flag: ${{ matrix.config.flag }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          # tsdk: these env vars are set in each of the actions
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_DIR }}
