name: Build Ios Static

env:
  project: PopH264

on:
  push:
    branches:
      - master
      - '*Test*' 

jobs:
  Build:
    name: Ios Static Library
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build Ios Static
        id: BuildIosStatic
        uses: NewChromantics/PopAction_BuildApple@v1.2.0
        with:
          BuildScheme: ${{ env.project }}_IosStatic
          project: ${{ env.project }}
          Destination: "generic/platform=iOS"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.BuildIosStatic.outputs.UPLOAD_NAME }}
          path: ${{ steps.BuildIosStatic.outputs.UPLOAD_DIR }}
