name: Build Visionos Static

env:
  project: PopH264

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Build:
    name: Tvos Static Library
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build VisionOS Static
        id: BuildVisionosStatic
        uses: NewChromantics/PopAction_BuildApple@v1.2.0
        with:
          BuildScheme: ${{ env.project }}_VisionosStatic
          project: ${{ env.project }}
          Destination: "generic/platform=visionOS"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.BuildVisionosStatic.outputs.UPLOAD_NAME }}
          path: ${{ steps.BuildVisionosStatic.outputs.UPLOAD_DIR }}
