name: Build Apple

env:
  project: PopH264

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*Test*' 
      - '*Workflow*'

jobs:
  Build:
    name: Apple Universal Framework
    runs-on: macos-15
    steps:
      - name: "Import Apple-Distriubution NewChromantics Signing Certificate"
        uses: NewChromantics/import-signing-certificate@v1.0.1
        with:
          certificate-data: ${{ secrets.APPLE_DIST_NEWCHROMANTICS_P12 }}
          certificate-passphrase: ${{ secrets.APPLE_DIST_NEWCHROMANTICS_PASSWORD }}
          keychain-password: "Hello"
             
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build Universal
        id: Build
        uses: NewChromantics/PopAction_BuildApple@v1.3.2
        with:
          BuildScheme: ${{ env.project }}_Universal
          Project: ${{ env.project }}
          Destination: "platform=macOS" # has no effect, but gets passed to xcodebuild so will fail if empty (todo: fix in action!)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.Build.outputs.UPLOAD_NAME }}
          path: ${{ steps.Build.outputs.UPLOAD_DIR }}
          if-no-files-found: error
