name: Build Android

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      project: PopH264
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build Android lib
      uses: NewChromantics/PopAction_BuildAndroid@v2
      with:
        buildscript: "PopH264.Android/build.sh"
        buildpath: "PopH264.Android/libPopH264"
        
    - name: Build Android test app
      uses: NewChromantics/PopAction_BuildAndroid@v2
      with:
        buildscript: "PopH264.Android/build.sh"
        buildpath: "PopH264.Android/PopH264TestApp"
