name: Build Android

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      project: PopH264
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build Android lib
      id: Build
      uses: NewChromantics/PopAction_BuildAndroid@v2.0.1
      with:
        buildtargetname: "PopH264"
        buildpath: "PopH264.Android/libPopH264"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.Build.outputs.UPLOAD_NAME }}
        path: ${{ steps.Build.outputs.UPLOAD_DIR }}
        if-no-files-found: error
